name: Build

on: push

jobs:
  jar:
    name: Create lambda
    runs-on: ubuntu-latest
    steps:

      - name: Checkout workspace
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build test

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: warn
          name: smart-home-alexaskill
          path: build/libs/smart-home-alexaskill-*.jar
